version: "3"

volumes:
  data:
  export:
  keycloak_data:
networks:
  idm_network:

services:
  postgres-db:
    image: docker.io/postgres:17-alpine
    container_name: postgres-server
    hostname: postgres-db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
    networks:
      - idm_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    ports:
      - "9990:8080"
      - "9991:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_METRICS_ENABLED: "false"
      KC_HEALTH_ENABLED: "false"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-db
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_LOG_LEVEL: INFO
    depends_on:
      - postgres-db
    command:
      - start-dev
      - --hostname=localhost
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./auth/import:/opt/keycloak/data/import
    networks:
      - idm_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9990/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped